'use strict';
const exportNumericKeys=new Set(['Results','Frequency','Cost per results','Ad set budget','Amount spent (INR)','CPM (cost per 1,000 impressions) (INR)','CPC (cost per link click) (INR)','CTR (link click-through rate)','Link to LP','Impressions','Hold Rate','Hook Rate','CTR (all)','Leads','Website leads','Meta leads','Website landing page views','Link clicks','Reach','CPC (all) (INR)','Purchases','In-app purchases','Website purchases','Offline purchases','Meta purchases','Meeting Booked']);
function reportExportRows(includeDeleted=false){return filtered(includeDeleted).filter(r=>(!r.deleted||+r.Impressions>0||+r['Amount spent (INR)']>0)&&r.delivery!=='In draft'&&(!state.selection.size||state.selection.has(r.id)))}
function reportExportValue(r,key){const v=key==='name'?r.name:key==='delivery'?r[singular[state.level]+' delivery']||r.delivery:r[key];return v!==''&&v!=null&&exportNumericKeys.has(key)&&Number.isFinite(Number(v))?Number(v):String(v??'')}
function reportSummaryValue(rows,key){if(key==='Frequency')return summaryFrequency(rows)??'';if(!['name','Reporting starts','Reporting ends'].includes(key)&&!rows.some(r=>r[key]!==undefined&&r[key]!==null&&r[key]!==''&&r[key]!=='-'))return '';const sum=k=>rows.reduce((n,r)=>n+(Number(r[k])||0),0);const spend=sum('Amount spent (INR)'),impressions=sum('Impressions'),clicks=sum('Link clicks');if(key==='name')return 'Summary';if(['Amount spent (INR)','Impressions','Link clicks','Leads','Website leads','Meta leads','Purchases','In-app purchases','Website purchases','Offline purchases','Meta purchases','Website landing page views','Meeting Booked'].includes(key))return sum(key);if(key==='CPM (cost per 1,000 impressions) (INR)')return impressions?spend/impressions*1000:'';if(key==='CPC (cost per link click) (INR)')return clicks?spend/clicks:'';if(key==='CTR (link click-through rate)')return impressions?clicks/impressions*100:'';return ''}
function buildReportExport({summary=false,includeDeleted=false}={}){const rows=reportExportRows(includeDeleted);const cols=[['Reporting starts','Reporting starts'],['Reporting ends','Reporting ends'],['name',singular[state.level]+' name'],...displayColumnKeys().filter(k=>!['actions','Reporting starts','Reporting ends','name'].includes(k)).map(k=>[k,k==='delivery'?singular[state.level]+' delivery':k.replace('(INR)','('+company.currency+')')])];const table=[cols.map(c=>c[1]),...rows.map(r=>cols.map(([key])=>key==='Reporting starts'?state.start:key==='Reporting ends'?state.end:reportExportValue(r,key)))];if(summary)table.push(cols.map(([key])=>reportSummaryValue(rows,key)));return {rows,cols,table}}
function createReportWorkbook(report){const X=window.XLSX;const sheet=X.utils.aoa_to_sheet(report.table);sheet['!cols']=report.cols.map(([key])=>({wch:key==='name'?60:/ID$/.test(key)?23:22}));sheet['!autofilter']={ref:X.utils.encode_range({r:0,c:0},{r:report.rows.length,c:report.cols.length-1})};const workbook=X.utils.book_new();X.utils.book_append_sheet(workbook,sheet,labels[state.level]);return workbook}
function csvReportText(table){return '\uFEFF'+table.map(row=>row.map(v=>{let value=String(v??'');if(typeof v==='string'&&/^[=+@\-\t\r]/.test(value))value="'"+value;return '"'+value.replaceAll('"','""')+'"'}).join(',')).join('\r\n')}
function exportReport(format='csv',options={}){const report=buildReportExport(options);const fallback=`${company.companyName}-${labels[state.level]}-${state.start}-${state.end}`;const name=(options.name||fallback).replace(/[\\/:*?"<>|\x00-\x1f]/g,'-').replace(/\.(csv|xlsx|xls)$/i,'').trim()||fallback;if(format==='csv')download(name+'.csv',csvReportText(report.table),'text/csv;charset=utf-8');else{if(!window.XLSX)return toast('Spreadsheet export library is unavailable. Reload this page.');const bytes=window.XLSX.write(createReportWorkbook(report),{bookType:format==='xls'?'biff8':'xlsx',type:'array',compression:true});download(name+'.'+format,bytes,format==='xls'?'application/vnd.ms-excel':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}toast(`Exported ${report.rows.length} ${labels[state.level].toLowerCase()} as .${format}.`)}
exportCSV=function(){exportReport('csv')};
showExport=function(){modal(`Export ${labels[state.level].toLowerCase()} table data – current view`,`<p>This file will only contain data from your current selection and will exclude ads that have not been published locally.</p><div class="export-column-note">The following column cannot be downloaded: Actions.</div><label class="field">Name your report<input id="export-name" value="${esc(`${company.companyName}, ${labels[state.level]}, ${dateText(state.start)}–${dateText(state.end)}`)}"></label><fieldset class="export-format-options"><legend>Select format</legend>${['csv','xlsx','xls'].map((f,i)=>`<label><input type="radio" name="report-format" value="${f}" ${i===0?'checked':''}>Export as .${f}</label>`).join('')}</fieldset><h4>Include additional data <span class="muted">∙ Optional</span></h4><label class="export-include"><input id="export-summary" type="checkbox">Include summary totals</label><label class="export-include"><input id="export-deleted" type="checkbox">Include deleted ads that contain delivery data</label>`,btn('Export','report-export-confirm','','primary'),650)};
const actionBeforeExports=action;
action=function(value,el){if(value==='export-menu'){menu(el,item('Export as .csv','report-export:csv')+item('Export as .xlsx','report-export:xlsx')+item('Customise export','custom-export')+item('Schedule export','schedule-export')+item('Share table link','share'),250);return}if(value.startsWith('report-export:')){exportReport(value.slice(14));return}if(value==='report-export-confirm'){const format=$('input[name="report-format"]:checked')?.value||'csv';exportReport(format,{name:$('#export-name').value,summary:$('#export-summary').checked,includeDeleted:$('#export-deleted').checked});$('#modal').close();return}return actionBeforeExports(value,el)};
