'use strict';
Object.assign(paths,{heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z',comment:'M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2V11.5a9.5 9.5 0 0 1 19 0z',bookmark:'M5 3h14v19l-7-5-7 5z',repost:'m4 7 4-4 4 4M8 3v14h12m0 0-4-4m4 4-4 4'});
let previewCreative=null,previewTab='Ad',previewGroup='All',previewShare=false,previewAdvanced=false;
const previewGroups=['All','Feeds, In-stream for reels','Stories, Status, Reels, Search results','Right column, Search results'];
function previewCTA(label,url){return creativeLink(label,url)||`<button class="pm-cta-unavailable" disabled title="Destination URL unavailable in this snapshot">${esc(label)}</button>`}
function previewAvatar(c){return c.pageAvatar?`<img class="pm-avatar" src="${esc(c.pageAvatar)}" alt="">`:'<span class="pm-avatar pm-avatar-empty">◉</span>'}
function previewCopy(c,instagram=false){const text=c.copy===undefined||c.copy===null?'Primary text unavailable':String(c.copy);const identity=instagram?`<b>${esc(c.instagramHandle||'Instagram account')}</b> `:'';if(!text)return '';if(text.length<=90)return `<div class="pm-copy pm-copy-short">${identity}${esc(text)}</div>`;return `<details class="pm-copy"><summary>${identity}${esc(text.slice(0,90))}… <span>more</span></summary><div>${esc(text)}</div></details>`}
function previewCard(c,instagram=false){const vertical=previewGroup===previewGroups[2],right=previewGroup===previewGroups[3];const identity=instagram?(c.instagramHandle||'Instagram account'):(c.page||'Facebook Page');const cta=(c.cta||'LEARN_MORE').toLowerCase().replaceAll('_',' ').replace(/^./,v=>v.toUpperCase());return `<article class="pm-card ${vertical?'pm-vertical':''} ${right?'pm-right':''}"><header>${previewAvatar(c)}<span><b>${esc(identity)}</b> ${c.verified?'<span class="pm-verified">✓</span>':''}<small>Ad ${instagram?'':'· 🌐'}</small></span><span class="pm-dots">···</span></header>${instagram?'':previewCopy(c)}<div class="pm-media">${c.video?`<video controls playsinline preload="none" ${c.image?`poster="${esc(c.image)}"`:""} aria-label="Video preview for ${esc(c.name)}"><source src="${esc(c.video)}">Your browser cannot play this video.</video>`:c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}">`:'<div class="ad-placeholder">Media unavailable in export</div>'}${c.videoId&&!c.video?'<span class="pm-video">▶ Video thumbnail</span>':''}</div>${instagram?`<div class="pm-instagram-cta">${previewCTA(cta,c.url)} <span>›</span></div><div class="pm-instagram-social" aria-label="Preview interaction icons">${icon('heart')}${icon('comment')}${icon('repost')}${icon('send')}<span>${icon('bookmark')}</span></div>${previewCopy(c,true)}`:`<div class="pm-link"><b>${esc(c.headline||'')}</b>${previewCTA(cta,c.url)}</div>${previewEngagement(c)}<div class="pm-social">♡ Like　　Comment　　Share</div>`}</article>`}
function previewDestinationHTML(c){const p=c.previewDestination;if(p)return `<div class="pm-phone"><div class="pm-browser">×　‹ <span>Facebook<br>▣ ${esc(p.host)}</span> ›　···</div><div class="pm-skeleton" aria-label="Destination page layout preview"><i></i><i></i>${Array.from({length:5},()=>'<p><b></b><i></i></p>').join('')}</div><div class="pm-contact">${previewAvatar(c)}<span><b>${esc(p.page)}</b><small>${esc(p.phone)}</small></span><span class="pm-whatsapp">◉ ${esc(p.cta)}</span></div><div class="pm-phone-bottom">${icon('send')}${icon('bookmark')}<span>ⓘ</span>${icon('refresh')}</div></div>`;return `<div class="pm-destination"><h3>Website destination</h3><p>${esc(c.url||'Destination unavailable in export')}</p>${creativeLink('Open website',c.url)}<p class="muted small">Open the destination to see its current content.</p></div>`}
function previewShareHTML(c){return `<div class="pm-share-menu"><b>Share previews</b>${btn('Share a link','pm-copy-link')}<b>Preview on device</b>${['Send notification to Facebook (iOS only)','Feed ad: Send notification to Instagram','Story ad: send notification to Instagram'].map(x=>`<button disabled title="Requires a live Meta connection">${x}</button>`).join('')}<b>See post</b>${creativeLink('Facebook post with comments',c.permalink)}${creativeLink('Instagram post with comments',c.instagramUrl)}<b>View on Facebook</b>${creativeLink('Facebook desktop Feed',c.previewUrl)}<p class="small muted">Device notifications require Meta.</p></div>`}
function drawPreviewModal(){if(previewAdvanced){drawAdvancedPreview();return}const c=previewCreative;if(!c)return;const d=$('#modal');d.classList.remove('source-column-modal');d.classList.add('source-preview-modal');d.style.width='600px';d.innerHTML=`<div class="modal-head"><h2>Ad preview</h2>${ib('Close','close-modal','close')}</div><div class="pm-subhead"><b>Ad preview</b><div role="tablist">${['Ad','Destination'].map(t=>`<button role="tab" aria-selected="${previewTab===t}" data-action="pm-tab:${t}">${t}</button>`).join('')}</div></div>${previewTab==='Ad'?`<div class="pm-toolbar"><div class="pm-groups" role="tablist">${previewGroups.map((g,i)=>`<button role="tab" title="${g}" aria-label="${g}" aria-selected="${previewGroup===g}" data-action="pm-group:${i}">${icon(['grid','table','ad','columns'][i])}</button>`).join('')}</div><span class="pm-toolbar-space"></span>${btn('⛶','pm-advanced','','','title="Advanced preview" aria-label="Advanced preview"')}${btn('Share ⌄','pm-share')}${previewShare?previewShareHTML(c):''}</div><div class="pm-scroll"><div class="pm-grid">${previewCard(c)}${previewGroup===previewGroups[3]?'':previewCard(c,true)}</div><p class="pm-render-note">Ad rendering and interaction may vary based on device, format and other factors.</p><details class="pm-details"><summary>Ad details and performance</summary><h3>${esc(c.name)}</h3>${c.localPreview?'<p class="small muted">Local draft preview. Historical metrics below describe the imported ad, before these edits.</p>':''}${creativeMetricsHTML(c)}<dl>${[['Ad ID',c.adId],['Campaign',c.campaignName],['Ad set',c.adsetName],['Destination',c.url],['Image source',c.imageSource]].filter(x=>x[1]).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p class="small muted">Placement layouts are local approximations. Video playback is available when a local video file is supplied.</p></details></div>`:`<div class="pm-destination-pane">${previewDestinationHTML(c)}</div>`}<div class="modal-footer">${btn('OK','close-modal','','primary')}</div>`;$('#drawer').hidden=true;$('#popover').hidden=true;if(!d.open)d.showModal()}
showSourceCreative=function(c){$('#modal').classList.remove('pm-advanced');previewAdvanced=false;previewCreative=c;previewTab='Ad';previewGroup='All';previewShare=false;drawPreviewModal()};
const actionBeforePreviewModal=action;
action=function(value,el){if(value.startsWith('pm-tab:')){previewTab=value.slice(7);previewShare=false;drawPreviewModal();return}if(value.startsWith('pm-group:')){previewGroup=previewGroups[Number(value.slice(9))]||'All';drawPreviewModal();return}if(value==='pm-share'){previewShare=!previewShare;drawPreviewModal();return}if(value==='pm-copy-link'){const url=safeCreativeURL(previewCreative.previewUrl||previewCreative.permalink);if(url)navigator.clipboard.writeText(url).then(()=>toast('Original preview link copied')).catch(()=>toast('Could not copy the link'));else toast('No shareable preview link was included in the export');return}if(value==='pm-advanced'){previewAdvanced=true;drawAdvancedPreview();return}if(value==='pm-back'){previewAdvanced=false;$('#modal').classList.remove('pm-advanced');drawPreviewModal();return}if(value==='preview-selected'){const r=selectedRows()[0];if(r)showAdPreview(r);return}return actionBeforePreviewModal(value,el)};
const modalBeforePreviewModal=modal;
modal=function(...args){$('#modal').classList.remove('source-preview-modal','pm-advanced');return modalBeforePreviewModal(...args)};
const renderBeforePreviewModal=render;
render=function(){renderBeforePreviewModal();if(state.level==='ads')$('#toolbar').insertAdjacentHTML('beforeend',btn('Preview','preview-selected','image','',selectedRows().length===1?'':'disabled'))};
render();

const advancedPlacements=[['Facebook Feed',1],['Instagram Feed',1],['Instagram Stories',2],['Facebook Stories',2],['Facebook Marketplace',1],['Instagram Reels',2],['Instagram profile feed',1],['Facebook Reels',2],['Instagram search results',2],['Facebook profile feed',1],['Facebook in-stream reels',1],['Facebook right column',3],['Facebook search results',3],['Facebook notifications',1],['Instagram Explore home',1]];
function drawAdvancedPreview(){const c=previewCreative,d=$('#modal');d.classList.add('pm-advanced');d.innerHTML=`<div class="pm-advanced-head"><div><h2>Advanced preview</h2><p>Review your ad across placements. These local layouts use the artwork and copy available in the source export.</p></div>${ib('Close advanced preview','pm-back','close')}</div><div class="pm-toolbar"><div class="pm-advanced-groups" role="tablist">${previewGroups.map((g,i)=>`<button role="tab" aria-selected="${previewGroup===g}" data-action="pm-group:${i}">${icon(['grid','table','ad','columns'][i])}${g}</button>`).join('')}</div><span class="pm-toolbar-space"></span>${btn('Share ⌄','pm-share')}${previewShare?previewShareHTML(c):''}</div><div class="pm-advanced-scroll"><h3>Ways that your ad will be seen</h3><p class="small muted">Placement layout previews. Advantage+ variations are not included in this snapshot.</p><div class="pm-placement-gallery">${advancedPlacements.filter(([,g])=>previewGroup==='All'||previewGroup===previewGroups[g]).map(([name,g])=>{const previous=previewGroup;previewGroup=previewGroups[g];const card=previewCard(c,name.startsWith('Instagram'));previewGroup=previous;return `<section><div class="pm-placement-name">${name.startsWith('Instagram')?'◎':'ⓕ'} ${name}</div>${card}</section>`}).join('')}</div></div>`}

function previewEngagement(c){const reaction=c.previewReactionText?esc(c.previewReactionText):c.previewLikes!==undefined?num(c.previewLikes):'';const comments=c.previewComments!==undefined?`<span>${num(c.previewComments)} comments</span>`:'';const shares=c.previewShares!==undefined?`<span>${num(c.previewShares)} shares</span>`:'';return reaction||comments||shares?`<div class="pm-counts">${reaction?`<span>👍 ${reaction}</span>`:''}${comments}${shares}</div>`:''}
